services:
  recipeapp:
    image: recipeapp
    build:
      context: .
      dockerfile: RecipeApp/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"
    depends_on:
        - db
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=443
        - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        - ConnectionStrings__DefaultConnection=Server=db;Database=RecipeApp;User=sa;Password=Password123
  
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: Password123
        POSTGRES_USER: sa
        POSTGRES_DB: RecipeApp
    ports:
        - "5432:5432"
    volumes:
        - db-data:/var/lib/postgresql/data
    
volumes:
    db-data:

